exp_name: SPELL_VS_VideoXum_default
model_name: SPELL
graph_name: VideoXum_10_0
dataset: VideoXum
loss_name: bce_logit
use_spf: False
use_ref: False
num_modality: 1
channel1: 256
channel2: 128
final_dim: 1
num_att_heads: 0
dropout: 0.2
lr: 0.001
wd: 0.001
batch_size: 1
sch_param: 5
num_epoch: 5
sample_rate: 1
t_emb: True
k: 5
eps: 0.5
use_mean_sum: True
norm: True
tau: 2